# MCU8 Bootloader Configuration

# Configuration Data Specific to the generated bootloader
[bootloader]
IMAGE_FORMAT_VERSION = "0.3.0"
PAGE_ERASE_KEY = 0x33CC
PAGE_WRITE_KEY = 0x22DD
PAGE_READ_KEY = 0x44BB
BYTE_WRITE_KEY = 0xAA55
DEVICE_ID = 0x00007180
WRITE_BLOCK_SIZE = 0x100
FLASH_START = 0x00002000
FLASH_END = 0x010000
EEPROM_START = 0x310000
EEPROM_END = 0x3103FF
CONFIG_START = 0x300000
CONFIG_END = 0x30000B
ARCH = "PIC18"
VERIFICATION = "CRC-16"

# Data needed by the host
[host]
coms = "UART"